#!/bin/bash

#using the logical And n logical OR operators

[ -z $1 ] && echo No input is provided && exit 2
[ -d $1 ] && echo $1 is a directory && exit 0
[ -f $1 ] && echo $1 is a file || echo $1 is not a file nor a directory
